Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define "db01" do |db01|
        db01.vm.box = "eurolinux-vagrant/centos-stream-9"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.51"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end

        db01.vm.provision "shell", path: "mysql.sh"
    end

    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.52"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end

        mc01.vm.provision "shell", path: "memcached.sh"
    end

    config.vm.define "rc01" do |rc01|
        rc01.vm.box = "eurolinux-vagrant/centos-stream-9"
        rc01.vm.hostname = "rc01"
        rc01.vm.network "private_network", ip: "192.168.56.53"
        rc01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end

        rc01.vm.provision "shell", path: "rabbitmq.sh"
    end

    config.vm.define "app01" do |app01|
        app01.vm.box = "eurolinux-vagrant/centos-stream-9"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", ip: "192.168.56.54"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end

        app01.vm.provision "shell", path: "tomcat.sh"
    end

    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.55"
        web01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end

        web01.vm.provision "shell", path: "nginx.sh"
    end
end