Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

#  DB VM
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.20"
    db01.vm.provider "virtulabox" do |vb|
        vb.memory = "2048"
    end
  end

  # Memcached vm
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.45.21"
    mc01.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
  end

  #Rabbit mq
  config.vm.define "rc01" do |rc01|
    rc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rc01.vm.hostname = "rc01"
    rc01.vm.network "private_network", ip: "192.168.56.22"
    rc01.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
  end

  #tomcat vm
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.23"
    app01.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
  end

  #nginx vm
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.24"
    web01.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
  end
end